---
name: Create Release Pull Request
on:
  workflow_dispatch:
    inputs:
      repo_version:
        description: 'Commit to release'
        required: true

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.repo_version }}

      - name: Create branch for pull Request
        id: cb
        run: |
          git checkout -b to-be-pulled ${{ github.event.inputs.repo_version }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          base: release
          branch: to-be-pulled
